Add support for PancakeSwap V3
Aperture-Finance/Aperture-Lens pull request #11
Opened 2024-03-29 19:24 UTC by gnarlycow

2024-03-31 02:15 UTC, shuhuiluo requested changes

2024-03-31 02:15 UTC, shuhuiluo commented on contracts/PCSV3PositionUtils.sol
> +    uint32 feeProtocol;
Can change the original `Slot0. feeProtocol` to `uint32` and reduce a lot of duplicates.

2024-03-31 06:48 UTC, shuhuiluo requested changes

2024-03-31 06:48 UTC, shuhuiluo commented on contracts/EphemeralPoolSlots.sol
> +                    slot0 := or(shl(216, observationCardinalityNext), slot0)
```suggestion
                    slot0 := shl(216, observationCardinalityNext)
```

2024-03-31 06:48 UTC, shuhuiluo commented on test/foundry/PositionLens.t.sol
> +    }
```suggestion
```

2024-03-31 06:48 UTC, shuhuiluo commented on test/foundry/PositionLens.t.sol
> +            ) = getPoolSlot0(pool);
```suggestion
            ) = IPancakeV3Pool(pool).slot0();
```

2024-03-31 06:48 UTC, shuhuiluo commented on test/foundry/PositionLens.t.sol
> +    }
```suggestion
```

2024-04-01 16:43 UTC, shuhuiluo requested changes

2024-04-01 16:43 UTC, shuhuiluo commented on package.json
> +    "@aperture_finance/uniswap-v3-automation-sdk": "3.0.0-alpha",
Circular dependency.

2024-04-01 21:27 UTC, gaohan137 approved these changes

2024-04-01 21:31 UTC, merged